import type { Metadata } from 'next';
import './globals.css';
import StoreProvider from '@/app/StoreProvider';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: '#FF8800'
              }
            }}>
            <AntdRegistry>{children}</AntdRegistry>
          </ConfigProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
